name: release
on:
  workflow_call:
    inputs:
      container:
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo release

  push:
    if: inputs.container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo push
